"""Added required tables

Revision ID: 393b067f3b97
Revises: 8f27d0b48194
Create Date: 2023-06-01 13:28:21.409884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393b067f3b97'
down_revision = '8f27d0b48194'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'name')
    # ### end Alembic commands ###
